[[constraint]]
  name = "github.com/go-kit/kit"
  version = "0.7.0"

[[constraint]]
  name = "github.com/go-redis/redis"
  version = "6.14.1"

[[constraint]]
  name = "github.com/go-yaml/yaml"
  version = "2.2.1"

[[constraint]]
  name = "github.com/pkg/errors"
  version = "0.8.0"

[prune]
  go-tests = true
  unused-packages = true

[[constraint]]
  name = "github.com/jinzhu/gorm"
  version = "1.9.14"
